name: koye_kos
description: Find and recommend awesome camping spots

version: 2.1.4+94

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Firebase/Google
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  cloud_firestore: ^3.1.4
  firebase_dynamic_links: ^4.0.2
  firebase_storage: ^10.2.3
  firebase_crashlytics: ^2.4.3
  firebase_remote_config: ^2.0.0
  cloud_functions: ^3.2.11

  #auth
  flutterfire_ui: ^0.4.0
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^4.1.1
  sign_in_with_apple: ^3.2.0
  sign_button:
    git:
      url: https://github.com/samu-developments/Flutter-Sign-in-Button-1.git

  # State
  flutter_riverpod: ^1.0.3

  #Routing
  auto_route: ^3.2.4

  # Map
  mapbox_gl: ^0.15.0
  geolocator: ^8.0.0
  mapbox_search: ^3.0.1+1
  material_floating_search_bar: ^0.3.6
  geocoding: ^2.0.1
  maps_toolkit: ^2.0.0

  # sharing
  map_launcher: ^2.1.1
  url_launcher: ^6.0.12
  share_plus: ^4.0.4
  uni_links: ^0.5.1

  # image
  image_picker: ^0.8.4+4
  cached_network_image: ^3.1.0+1
  transparent_image: ^2.0.0
  image_cropper: ^1.4.1
  photo_view: ^0.14.0
  flutter_image_compress: ^1.0.0
  flutter_svg: ^1.0.0

  # Misc/utils
  shared_preferences: ^2.0.8
  animations: ^2.0.0
  font_awesome_flutter: ^10.1.0
  implicitly_animated_reorderable_list: ^0.4.2
  connectivity_plus: ^2.3.0
  introduction_screen: ^3.0.0
  stream_transform: ^2.0.0
  flutter_styled_toast: ^2.0.0
  dio: ^4.0.0
  crypto: ^3.0.1
  upgrader: ^4.0.0
  badges: ^2.0.1
  collection: ^1.15.0
  translator: ^0.1.7
  expandable: ^5.0.1
  package_info_plus: ^1.3.0
  settings_ui: ^2.0.2
  basic_utils: ^4.2.0
  flutter_slidable: ^1.2.0
  flutter_native_splash: ^2.1.6
  showcaseview: ^1.1.5
  flutter_html: ^3.0.0-alpha.3

  # billing
  in_app_purchase: ^3.0.2

  smooth_star_rating_v2:
    git:
      url: https://github.com/samu-developments/smoothratingbar.git

  # web
  pointer_interceptor: ^0.9.0+1

  # code generation / serialization
  freezed_annotation: ^2.0.1
  json_serializable: ^6.1.1
  json_annotation: 4.5.0

  #internationalization
  intl: ^0.17.0

dependency_overrides:
  # flutter 3 issues
  flutter_styled_toast: 2.0.0
  flutter_slidable: 1.2.0
  flutter_native_splash: 2.1.6
  flutter_riverpod: 1.0.3
  flutterfire_ui: 0.4.0
  upgrader: 4.0.0
  auto_route: 3.2.4
  cached_network_image: 3.2.0

  mapbox_gl:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      #ref: 'b28e8c6194da448cf7c26514e1331e401010f905' # https://github.com/flutter-mapbox-gl/maps/issues/771
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      path: mapbox_gl_platform_interface
      #ref: 'b28e8c6194da448cf7c26514e1331e401010f905' # https://github.com/flutter-mapbox-gl/maps/issues/771

  mapbox_gl_web:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      path: mapbox_gl_web
      #ref: 'b28e8c6194da448cf7c26514e1331e401010f905' # https://github.com/flutter-mapbox-gl/maps/issues/771


dev_dependencies:
  test: ^1.17.4
  build_runner: ^2.1.5
  freezed: ^2.0.2
  auto_route_generator: ^3.2.3
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/symbols/location_red.png
    - assets/symbols/2.0x/location_red.png
    - assets/symbols/3.0x/location_red.png
    - assets/symbols/location_black.png
    - assets/symbols/2.0x/location_black.png
    - assets/symbols/3.0x/location_black.png
    - assets/symbols/location_grey.png
    - assets/symbols/2.0x/location_grey.png
    - assets/symbols/3.0x/location_grey.png
    - assets/symbols/location_orange.png
    - assets/symbols/2.0x/location_orange.png
    - assets/symbols/3.0x/location_orange.png
    - assets/screenshot.jpg
    - assets/apple_168.png
    - assets/google_250.png
    - assets/icon/sweetspots.png
    - assets/icon/sweetspots_no_bg.png
