name: koye_kos
description: Find and recommend awesome camping spots

version: 4.0.2+118

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Firebase/Google
  cloud_firestore: ^4.0.0
  cloud_functions: ^4.0.0
  firebase_analytics: ^10.0.0
  firebase_auth: ^4.0.0
  firebase_core: ^2.0.0
  firebase_crashlytics: ^3.0.0
  firebase_dynamic_links: ^5.0.0
  firebase_remote_config: ^3.0.0
  firebase_storage: ^11.0.0

  #auth
  google_sign_in: ^6.0.0
  flutter_facebook_auth: ^5.0.0
  sign_in_with_apple: ^4.1.0
  sign_button:
    git:
      url: https://github.com/samu-developments/Flutter-Sign-in-Button-1.git

  # State
  flutter_riverpod: ^2.0.0

  #Routing
  auto_route: ^5.0.0

  # Map
  geolocator: ^9.0.0
  mapbox_search: ^3.0.0
  material_floating_search_bar: ^0.3.0
  geocoding: ^2.0.0
  maps_toolkit: ^2.0.0

  # sharing
  map_launcher: ^2.1.0
  url_launcher: ^6.1.0
  share_plus: ^6.0.0
  uni_links: ^0.5.0

  # image
  image_picker: ^0.8.0
  cached_network_image: ^3.1.0
  transparent_image: ^2.0.0
  image_cropper: ^3.0.0
  photo_view: ^0.14.0
  flutter_image_compress: ^1.0.0
  flutter_svg: ^2.0.0

  # Misc/utils
  shared_preferences: ^2.0.0
  animations: ^2.0.0
  font_awesome_flutter: ^10.1.0
  connectivity_plus: ^3.0.0
  introduction_screen: ^3.0.0
  stream_transform: ^2.0.0
  flutter_styled_toast: ^2.0.0
  dio: ^5.0.0
  crypto: ^3.0.0
  upgrader: ^6.0.0
  badges: ^3.0.2
  collection: ^1.16.0
  translator: ^0.1.0
  expandable: ^5.0.0
  package_info_plus: ^3.0.0
  settings_ui: ^2.0.0
  basic_utils: ^5.1.0
  flutter_slidable: ^2.0.0
  flutter_native_splash: ^2.2.0
  showcaseview: ^2.0.0
  flutter_html: ^3.0.0-alpha.3

  # billing
  in_app_purchase: ^3.0.0

  smooth_star_rating_v2:
    git:
      url: https://github.com/samu-developments/smoothratingbar.git

  # web
  pointer_interceptor: ^0.9.0

  # code generation / serialization
  freezed_annotation: ^2.0.0
  json_serializable: ^6.1.0
  json_annotation: ^4.8.0

  #internationalization
  intl: ^0.18.0

  mapbox_maps_flutter: ^0.4.0
  turf: ^0.0.7

dependency_overrides:
  settings_ui:
    git:
      url: https://github.com/yako-dev/flutter-settings-ui.git

dev_dependencies:
  test: ^1.21.0
  build_runner: ^2.1.0
  freezed: ^2.0.0
  auto_route_generator: ^5.0.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/symbols/location_red.png
    - assets/symbols/2.0x/location_red.png
    - assets/symbols/3.0x/location_red.png
    - assets/symbols/location_black.png
    - assets/symbols/2.0x/location_black.png
    - assets/symbols/3.0x/location_black.png
    - assets/symbols/location_grey.png
    - assets/symbols/2.0x/location_grey.png
    - assets/symbols/3.0x/location_grey.png
    - assets/symbols/location_orange.png
    - assets/symbols/2.0x/location_orange.png
    - assets/symbols/3.0x/location_orange.png
    - assets/screenshot.jpg
    - assets/apple_168.png
    - assets/google_250.png
    - assets/icon/sweetspots.png
    - assets/icon/sweetspots_no_bg.png
    - assets/icon/sweetspots_icon_new.svg
    - assets/icon/sweetspots_icon_new_trimmed.svg
